### PR TITLE
Update CircleCI badge in README.md

### PR DESCRIPTION
**Pull request by wojsmol**

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]
Thanks, @wojsmol !

The URL is dynamically generated, so we'll need to fix #204 for the change to be persistent.

We can land this for now, though.

**Comment by wojsmol** [comment]
@danielbachhuber This is for this repo `README.md` badge not for generated `README.md` file.

**Comment by danielbachhuber** [comment]
> This is for this repo `README.md` badge not for generated `README.md` file.

@wojsmol Yep! In the past at least, the `README.md` for this repo was dynamically generated.

**Comment by wojsmol** [comment]
@danielbachhuber You are right this repo `README.md` is automatically generated using this command - see my comment https://github.com/wp-cli/scaffold-package-command/issues/204#issuecomment-1208155437.

**Pull request merged**
