### PR TITLE
Convert '~/' when supplied in `$package_dir`

### LINKED ISSUE #119: The scaffold package `--dir=<dir>` argument does not use `realpath`
When using a path like `--dir=~/<package-name>` with `wp scaffold package`, I would expect WP-CLI to resolve this to actually create the folder `/home/<user>/<package-name>` or any similar platform-specific version of it.

However, WP-CLI actually creates the literal folder `'~'` and puts everything into that folder.

It should probably use something like `realpath()` before creating the folders.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #119

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera I'm not sure `realpath()` is the way to go because:

> The running script must have executable permissions on all directories in the hierarchy, otherwise `realpath()` will return FALSE.

Thoughts?

**Comment by schlessera** [comment]
Maybe use our own helper functions, something like this: https://3v4l.org/9Ga8c

**Comment by schlessera** [comment]
Drush uses this: https://github.com/webmozart/path-util

**Comment by gitlost** [comment]
As it's very Unixy could just do something like
```php
if ( '~/' === substr( $package_dir, 0, 2 ) && ( $home = getenv( 'HOME' ) ) ) {
	$package_dir = $home . substr( $package_dir, 1 );
}
```

**Comment by schlessera** [comment]
@gitlost Yes, I suggested a more robust version of that here: https://3v4l.org/9Ga8c

**Comment by danielbachhuber** [comment]
@schlessera @gitlost Updated. I went with the simpler approach to begin with.

**Comment by schlessera** [comment]
I'm not sure why you'd want to solve this partially only. It is highly probable someone will want to use a relative path with this as well, and just create a new bug report at that point.

Additionally, having `~` work, and not `.` or `..` makes it even worse in that it is inconsistent as well.

**Comment by gitlost** [comment]
I don't see how a relative path or `.` or `..` won't just work - just tried `--dir=~/../blah` and it worked...

**Comment by schlessera** [comment]
Oh, okay, I just assumed it would create issues as well. All good then.

**Pull request merged**
