### PR TITLE
Fix typo in package-readme command doc

### PR DESCRIPTION
**Pull request by ernilambar**
**Path:** `src/ScaffoldPackageCommand.php` L220

**Current:**

`underlaying`

**Changed to:**

`underlying`

### CODE REVIEW

**Comment by swissspidy** [comment]
@ernilambar Thanks for fixing all these typos everywhere. Instead of doing all of that manually, it would be easiest to just set up a GitHub Action to do this. See https://github.com/WordPress/plugin-check/blob/571a65a3f993fcc5bb7faf04fbb5d16c696cd599/.github/workflows/spell-check.yml for an example.

This could be added to https://github.com/wp-cli/.github/tree/7f6b72e950f06caabb5e8875e1f85f4a561cb63b/.github/workflows and all WP-CLI repositories would automatically benefit from automated spell check.

Would you be interested in submitting a PR for that?

**Review by swissspidy — APPROVED** [review]

**Comment by ernilambar** [comment]
@swissspidy Sure. I will try that approach.

**Comment by ernilambar** [comment]
@swissspidy Should this Spell Check action be kept inside `workflows/reusable-code-quality.yml` file?

**Comment by swissspidy** [comment]
Sure that works

**Pull request merged**
